In [2]:
import numpy as np

In [3]:
np.pi

3.141592653589793

In [4]:
np.random.randint(0, 10, 2)

array([6, 5])

In [5]:
np.random.seed(1337)
np.random.randint(0, 10, 2)

array([7, 8])

In [6]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [9]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
a.flatten()

array([0, 1, 2, 3, 4, 5])

In [11]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
np.log(a)

/opt/conda/envs/python2/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791]])

In [13]:
np.amin(a)

0

In [14]:
np.amin(a, axis = 0)

array([0, 1, 2])

In [15]:
np.amin(a, axis = 1)

array([0, 3])

In [16]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
np.amax(a)

5

In [18]:
np.amax(a, axis = 0)

array([3, 4, 5])

In [19]:
np.amax(a, axis = 1)

array([2, 5])

In [20]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
np.argmin(a, axis = 0)

array([0, 0, 0])

In [22]:
np.argmax(a, axis = 1)

array([2, 2])

In [23]:
np.argmax(a)

5

In [24]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
np.sum(a, axis = 1)

array([ 3, 12])

In [26]:
np.mean(a, axis = 0)

array([1.5, 2.5, 3.5])

In [27]:
b = np.array([0, 1, 1, 3, 2, 1, 7])
b

array([0, 1, 1, 3, 2, 1, 7])

In [28]:
np.bincount(b)

array([1, 3, 1, 1, 0, 0, 0, 1])

In [29]:
np.array_equal([1, 2], [1, 2])

True

In [30]:
np.array_equal([1, 2], [1, 2, 3])

False

In [31]:
np.allclose([1e10,1e-7], [1.00001e10,1e-8])

False

In [32]:
np.allclose([1e10,1e-8], [1.00001e10,1e-9])

True